<form action="index.php?route=check_create_user" method="post">
    <fieldset>
        <label for="email">Email</label>
        <input type="email" name="email" id="email"/>
    </fieldset>
    <fieldset>
        <label for="firstname">Prénom</label>
        <input type="text" name="first_name" id="firstname"/>
    </fieldset>
    <fieldset>
        <label for="lastname">Nom</label>
        <input type="text" name="last_name" id="lastname"/>
    </fieldset>
    <fieldset>
        <input type="submit" value="Inscription"/>
    </fieldset>
</form>